typeidea/typeidea/urls.py
from django.conf.urls import url
from django.contrib import admin

from custom_site import custom_site
from blog.views import  *
from config.views import *
from comment.views import *

urlpatterns = [
    #主页
    url(r'^$',IndexView.as_view(),name='index'),
    #分类页
    url(r'^category/(?P<category_id>\d+)/$',CategoryView.as_view(),name='category-list'),
    #我们在地址栏写的参数会传递到类中存放在 self.kwargs中，是一个字典
    url(r'^tag/(?P<tag_id>\d+)/$',TagView.as_view(),name='tag-list'),
    url(r'^post/(?P<pk>\d+)/$',PostDetailView.as_view(),name='post-detail'),
    #搜索
    url(r'^search/$',SearchView.as_view(),name='search'),
    #作者页面
    url(r'^about/(?P<id>\d+)/$',AuthorView.as_view(),name='author-id'),
    #友情链接
    url(r'^links/$',LinkListView.as_view(),name='links'),
    #评论
    url(r'^comment/$',CommentView.as_view(),name='comment'),
    url(r'^super_admin/',admin.site.urls,name='super-admin'),
    url(r'^admin/', custom_site.urls,name='admin'),#引入我们自定义的site
]

typeidea/comment/models.py
from django.db import models

# Create your models here.
from blog.models import Post
class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除')
    )
    target = models.CharField(max_length=100,verbose_name='评论目标')
    content = models.CharField(max_length=2000,verbose_name='内容')
    nickname = models.CharField(max_length=30,verbose_name='昵称')
    website = models.URLField(verbose_name='网站')
    email = models.EmailField(verbose_name='邮箱')
    status = models.PositiveIntegerField(default=1,choices=STATUS_ITEMS,verbose_name='状态')
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    @classmethod
    def get_by_target(cls,target):
        return cls.objects.filter(target=target,status=cls.STATUS_NORMAL)


    class Meta:
        db_table = 'comment'
        verbose_name = verbose_name_plural = '评论'

typeidea/comment/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class':'form-control','style':'width:60%'}
        )
    )
    email = forms.CharField(
        label='邮箱',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class':'form-control','style':"width:60%"}
        )
    )
    website = forms.CharField(
        label='网站',
        widget=forms.widgets.URLInput(
            attrs={'class':'form-control','style':'width:60%'}
        )
    )
    content = forms.CharField(
        label='内容',
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'class':'form-control','rows':6,'cols':60}
        )
    )

    #对数据的一些验证 类似 flask-wtf 的validat_%
    def clean_content(self):
        content = self.cleaned_data.get('content')
        if len(content) < 2:
            raise forms.ValidationError('内容长度太短!')
        return content
    class Meta:
        model = Comment
        fields = ['nickname','email','website','content']

typeidea/comment/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
# Create your views here.
from .models import *
from .forms import *
class CommentView(TemplateView):
    http_method_names = ['post'] #设置接受请求为post
    template_name = 'comment/result.html'

    def post(self,request,*args,**kwargs):

        comment_form = CommentForm(request.POST)
        target = request.POST.get('target',None)
        print(target)
        # print(target)
        # print(comment_form.data)
        # print(comment_form.is_valid())
        # print(comment_form.errors)
        # print(comment_form.cleaned_data)


        if comment_form.is_valid():

             instance = comment_form.save(commit=False) #获取数据生成数据库对象，但不提交
             instance.target = target
             instance.save()
             succeed = True
             return redirect(target)
        else:
            succeed = False

        context = {
            'succeed':succeed,
            'form':CommentForm,
            'target':target,
        }
        return self.render_to_response(context)

typeidea/typeidea/themes/bootstrap/templates/comment/block.html
<div class="comment">
    <form class="form-group" action="/comment/" method="post">
        {% csrf_token %}
        <input name="target" type="hidden" value="{{ target }}">
        {{ comment_form }}
        <input type="submit" value="写好了!">
    </form>
    <!-- 评论列表 -->
    <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">
            <div class="nickname">
                <a href="{{ comment.website }}">{{ comment.nickname }}</a>
                <span>评论时间:{{comment.created_time}}</span>
            </div>
            <div class="comment-content">
                {{ comment.content }}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

typeidea/typeidea/themes/bootstrap/templates/comment/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论结果页</title>
    <style>
        body{text-align: center}
        .result{
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist{color: red}
        ul li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <div class="result">
        {% if suceed %}
        评论成功！
        <a href="{{ target }}">..返回</a>
        {% else %}
            <ul class="errorlist">
                {% for msg in form.errors.items %}
                <li>{{msg}}</li>
                {% endfor %}
            </ul>
        <a href="javascript:window.history.back();">返回</a>
        {% endif %}
    </div>
</body>
</html>